language: php
sudo: required
dist: trusty
php:
  - 5.6
  - 7.0

env:
  global:
    - CORE_BRANCH=stable10
    - APP_NAME=search_lucene

  matrix:
    - DB=sqlite

branches:
  only:
    - master
    - /^stable\d+(\.\d+)?$/

before_install:
#  - composer install
  - which php
  - more `which pecl`
  - which phpize
  - bash tests/.travis/before_install.sh $APP_NAME $CORE_BRANCH $DB
  - cd ../core
  - php occ app:enable $APP_NAME

script:
  # Test lint
  - cd apps/$APP_NAME
  - sh -c "if [ '$DB' = 'sqlite' ]; then ant test; fi"

  # Run phpunit tests
  - cd tests/unit
  - ../../../../lib/composer/bin/phpunit --configuration phpunit.xml

  # Create coverage report
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml

matrix:
  include:
    - php: 7
      env: DB=mysql
    - php: 7
      env: DB=pgsql
    - php: 7
      env: DB=oracle

  fast_finish: true
